import SiteNav from '@/components/SiteNav'
import SiteFooter from '@/components/SiteFooter'

// ── Terms & Conditions content (from INMIX AI LLC legal disclosures) ──────────
const intro = [
  'These Terms & Conditions ("Terms") constitute a legally binding agreement between you ("User," "Client," "Artist," or "Producer") and INMIX AI LLC ("Company," "we," "us," or "our") concerning your access to and use of the inmix.ai website and automated AI mixing applications.',
  'By accessing the Website or executing a mix, you agree to be bound by these Terms. If you do not agree, you must immediately cease using the Service.',
]

type Block =
  | { type: 'p'; text: string }
  | { type: 'group'; text: string }
  | { type: 'item'; label: string; text: string }
  | { type: 'bullet'; text: string }

const sections: { title: string; blocks: Block[] }[] = [
  {
    title: '2.1 Eligibility and Account Registration',
    blocks: [
      { type: 'p', text: 'To access specific enterprise or DAW-integrated software tools, you must create an account.' },
      { type: 'p', text: 'You agree to provide accurate, current, and complete registration information and maintain the security of your account credentials.' },
      { type: 'p', text: 'You are entirely responsible for all activities, asset uploads, and commercial mixes generated under your account.' },
    ],
  },
  {
    title: '2.2 Intellectual Property Rights',
    blocks: [
      { type: 'group', text: 'A. Your Content and Audio Ownership' },
      { type: 'item', label: 'Retention of Rights', text: 'You retain 100% ownership, copyright, and master rights to all audio stems, arrangements, vocals, musical components, and finalized mixes uploaded to or generated by the inmix.ai platform.' },
      { type: 'item', label: 'License to Company', text: 'You grant INMIX AI LLC a limited, non-exclusive, worldwide, royalty-free, temporary license to host, parse, transmit, and run our AI algorithms over your uploaded audio files solely for the purpose of providing the mixing service to you. This license terminates automatically when you delete your files or account.' },
      { type: 'group', text: 'B. Company Property' },
      { type: 'p', text: 'The inmix.ai platform, including its user interface, algorithms, proprietary automated mixing logic, automated DAW template systems, website code, layout, design, trademarks, and the underlying technology protected under U.S. Patent #11929098 (or related pending applications), is the exclusive intellectual property of INMIX LLC.' },
      { type: 'p', text: 'You may not reverse-engineer, decompile, scrape, copy, or replicate our AI engine, mixing template architectures, or automated processing workflows.' },
    ],
  },
  {
    title: '2.3 Usage Restrictions and Acceptable Use',
    blocks: [
      { type: 'p', text: 'You explicitly agree that you will not use the Service to upload or process audio files that:' },
      { type: 'bullet', text: 'Infringe upon the copyright, trademark, or intellectual property rights of any third-party artist, sample library, or label.' },
      { type: 'bullet', text: 'Contain malicious code, viruses, or data intended to disrupt or damage our cloud hosting environment or processing infrastructure.' },
      { type: 'bullet', text: 'Attempt to bypass or exploit subscription tiers, API rate limits, or software integration endpoints.' },
    ],
  },
  {
    title: '2.4 Fees, Subscriptions, and Commercial Terms',
    blocks: [
      { type: 'item', label: 'SaaS Tiers & Enterprise Accounts', text: 'Certain features, high-resolution WAV rendering, and DAW enterprise plugins require paid subscription plans or enterprise-level licensing.' },
      { type: 'item', label: 'Billing Cycles', text: 'Subscriptions are billed automatically on a recurring basis (monthly or annually).' },
      { type: 'item', label: 'Refund Policy', text: 'Due to the compute-intensive nature of immediate AI file rendering and generation, payments are non-refundable unless specified otherwise in writing or required by consumer law. You may cancel your subscription at any time to prevent future billing.' },
    ],
  },
  {
    title: '2.5 Disclaimer of Warranties',
    blocks: [
      { type: 'p', text: 'The automated mixing services are provided on an "AS IS" and "AS AVAILABLE" basis. While our platform is driven by state-of-the-art patented AI and template matching protocols, INMIX LLC makes no warranties, express or implied, that the generated mix will meet your subjective creative preferences, commercial chart standards, or specific broadcast specifications perfectly without manual adjustment. We do not guarantee uninterrupted or error-free server runtimes during periods of extreme processing demand.' },
    ],
  },
  {
    title: '2.6 Limitation of Liability',
    blocks: [
      { type: 'p', text: 'To the maximum extent permitted by applicable law, in no event shall INMIX LLC, its founders, directors, employees, or partners be liable for any indirect, incidental, special, exemplary, or consequential damages arising out of or in connection with your use of the automated mixing tools, loss of audio data, or failure of an upload, even if advised of the possibility of such damages. Our total liability to you for any claim arising out of these terms shall not exceed the amount paid by you to us in the six (6) months prior to the incident.' },
    ],
  },
  {
    title: '2.7 Governing Law and Dispute Resolution',
    blocks: [
      { type: 'p', text: 'These Terms and your use of the website are governed by and construed in accordance with the laws of the State of California or the State of Texas, without regard to conflict of law principles. Any legal action or proceeding arising out of these terms shall be brought exclusively in a court of competent jurisdiction located within that state.' },
    ],
  },
  {
    title: '2.8 Contact Information',
    blocks: [
      { type: 'p', text: 'For any legal questions regarding these Terms or our patented mixing technologies, please contact us at:' },
      { type: 'item', label: 'Entity', text: 'INMIX AI LLC' },
      { type: 'item', label: 'Email', text: 'Support@inmix.ai' },
      { type: 'item', label: 'Mailing Address', text: '24881 Alicia Pkwy Ste # E, Laguna Hills, CA 92653' },
    ],
  },
]

export default function Terms() {
  return (
    <div className="min-h-screen" style={{ background: '#07070b', color: 'var(--color-foreground)', fontFamily: 'inherit' }}>

      {/* ── NAVBAR ──────────────────────────────────────────────────────── */}
      <SiteNav />

      {/* ── HEADER ──────────────────────────────────────────────────────── */}
      <section className="relative pt-[200px] pb-12 px-6 text-center">
        <div className="relative z-10 max-w-3xl mx-auto">
          <div className="inline-flex items-center px-4 py-1.5 rounded-full text-[11px] font-normal tracking-[0.3em] uppercase mb-8"
               style={{ background: '#0011FF', color: '#ffffff' }}>
            Legal
          </div>
          <h1 className="mb-6 text-[48px] sm:text-[80px]"
              style={{ fontWeight: 300, lineHeight: '95%', color: '#ffffff' }}>
            Terms &amp; Conditions
          </h1>
          <p className="text-sm" style={{ color: '#ffffff' }}>
            INMIX AI LLC &nbsp;·&nbsp; Effective Date: June 8, 2026
          </p>
        </div>
      </section>

      {/* ── CONTENT ─────────────────────────────────────────────────────── */}
      <section className="px-6 pb-28">
        <div className="max-w-3xl mx-auto rounded-[32px] p-8 sm:p-12"
             style={{ border: '1px solid rgba(255,255,255,0.12)' }}>

          {intro.map((p, i) => (
            <p key={i} className="mb-5" style={{ fontSize: '17px', lineHeight: 1.6, color: '#ffffff' }}>{p}</p>
          ))}

          {sections.map(section => (
            <div key={section.title} className="mt-12">
              <h2 className="mb-5 text-[24px]" style={{ fontWeight: 500, color: '#ffffff' }}>
                {section.title}
              </h2>

              {section.blocks.map((block, i) => {
                if (block.type === 'p') {
                  return (
                    <p key={i} className="mb-4" style={{ fontSize: '17px', lineHeight: 1.6, color: '#ffffff' }}>
                      {block.text}
                    </p>
                  )
                }
                if (block.type === 'group') {
                  return (
                    <p key={i} className="mb-3 mt-6 text-sm font-semibold uppercase tracking-[0.15em]"
                       style={{ color: 'var(--color-primary)' }}>
                      {block.text}
                    </p>
                  )
                }
                if (block.type === 'bullet') {
                  return (
                    <div key={i} className="flex gap-3 mb-4">
                      <span className="mt-2.5 shrink-0" style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--color-primary)' }} />
                      <p style={{ fontSize: '17px', lineHeight: 1.6, color: '#ffffff' }}>{block.text}</p>
                    </div>
                  )
                }
                return (
                  <div key={i} className="flex gap-3 mb-4">
                    <span className="mt-2.5 shrink-0" style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--color-primary)' }} />
                    <p style={{ fontSize: '17px', lineHeight: 1.6, color: '#ffffff' }}>
                      <span style={{ fontWeight: 600 }}>{block.label}:</span> {block.text}
                    </p>
                  </div>
                )
              })}
            </div>
          ))}
        </div>
      </section>

      {/* ── FOOTER ───────────────────────────────────────────────────────── */}
      <SiteFooter />
    </div>
  )
}
